### ISSUE TITLE
How to detect, handle, and return errors?

### ISSUE THREAD

**Issue by grencez** [fildesh/fildesh#12]
## Task list

- [x] Test that overall script fails if one of its commands fails.
- [x] https://github.com/fildesh/fildesh/issues/46
- [x] https://github.com/fildesh/fildesh/issues/51
- [x] #61

## Original description

Bash has `set -o pipefail` to fail fast and the `PIPESTATUS` array to get statuses of programs in a pipeline (https://stackoverflow.com/questions/1550933/catching-error-codes-in-a-shell-pipe/9168523#comment40617017_9168523).

**Comment by grencez** [comment]
The current behavior is now to fail whenever a command fails. Nothing in the pipeline gets killed though.

**Comment by grencez** [comment]
Imagine a builtin meant to create a temporary file. The consumer(s) of that data would necessarily need to wait until all data is written, which we can only guarantee when the producer exits, thus forcing us to wait for the producer to exit before spawning the consumers or subsequent programs.

For error handling or early return, we generally want all processes in the current scope to be complete. Perhaps `barrier` is the right word. Or maybe `waitall`. I think we'd want to exit early on errors in most cases... perhaps there's a better word that captures that intent?

Anyway, I think this barrier mechanism would make more scripts possible. It should be sufficient to resolve this issue.

**Comment by grencez** [comment]
I think we're good on the whole philosophy of error handling now: All errors need to be caught with `$(O? ...)` and ideally checked with `expect_failure`.

We can also fail early with the help of barriers, but it's a bit awkward to carry data across those barriers. You basically need a file. Temporary files (https://github.com/fildesh/fildesh/issues/68) might make that easier in the future.
