### ISSUE TITLE
Make FildeshKV

### ISSUE THREAD

**Issue by grencez** [fildesh/fildesh#24]
as a hashmap with red-black tree buckets.

The keys can be 2 int_ptr_t, where one is number of bytes and the other is a pointer.

- [x] Make FildeshKVE: The key-value element.
- [x] Test performance of Associa vs a C++ map. Cry probably.
- [x] #79
- [x] #87
- [ ] #114
- [ ] Make freelist a doubly-linked list.
- [ ] Use fnv-1a hash function. Call the FildeshKV mode `fnv1a_rbtree`.
- [ ] After testing, make `fnv1a_rbtree` default.

**Comment by grencez** [comment]
The hash table itself can be a size_t array whose values are indices an array of red-black tree nodes. Ideally the table would be a power of 2, but some people use a prime size in order to mitigate funneling. http://databasearchitects.blogspot.com/2020/01/all-hash-table-sizes-you-will-ever-need.html would be a good resource here, but I need to research hash functions a bit more.

The red-black tree node array reserves 0 as a sentinel. Each node has several size_t fields:
- joint
- split[2]
- size: Top bit is set iff node is red. Second from top bit indicates that this node holds the key directly. In that case, the rest of the top byte holds the size and we have all but one of this field's bytes + the next field's to hold the key. Maybe include value too.
- key (actually a uintptr_t)
- value (actually a uintptr_t)
