### ISSUE TITLE
Heredoc as input file

### ISSUE THREAD

**Issue by grencez** [fildesh/fildesh#51]
## Task list

- [x] Support `$(XF var)` from a string definition `$(> var)` by adding another output to its associated `elastic` command.
- [x] Support `$(XF var)` from a heredoc `$(H var)` by creating a tmpfile like we do with `$(HF var)`.
- [x] Test the cases above.
- [x] Support & test the `$(X var)` syntax as well.
- [x] Deprecate the `$(HF var)` syntax.

## Description

It would be great to pass a heredoc to some program as file content like `$(XF my_heredoc)`.

We currently need an extra command to put that content into a pipe: 
```
$(H my_heredoc)
somethingsomething
$(H my_heredoc)

zec -o $(OF input_file) / $(XA my_heredoc) /
my_program $(XF input_file)
```

Well actually, there's an `HF` that works directly. But why is there a different thing?
