### ISSUE TITLE
Create Docker image and suggest using it to run examples

### ISSUE THREAD

**Issue by grencez** [fildesh/fildesh#63]
## Task List
It would be nice to run `fildesh` with a well-defined attack surface. Docker seems to be the best way to accomplish this.
- [x] Create Docker image.
- [x] Update README.md to mention Docker image.
- [x] Update SECURITY.md to mention Docker image.

## Original Description
I initially had some other ideas:
- Separate executable with certain functions compiled out.
  - Easy for scripts to opt into this version in their shebang line.
  - Maybe called `fildesh_strict`.
- Forbid accessing files that were not specified in command line args.
  - Can program lock itself down via AppArmor?
  - Forbid external programs (unless linked in as builtins?).
  - No tempfiles.
  - No network access.
- Allow some system resources that would be considered "impure".
  - File descriptors. Obviously.
  - Random numbers.
  - A monotonic clock.
